[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ledgerdrive = "GERZ7aGf8eVmLBpA1hoFJx2AnZXUKxmwYdQqoTdbPPND"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/arbazshaikh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
